// Re-export Prisma client
export { prisma, PrismaClient } from './client';
export type { Prisma } from './client';

// Re-export all Prisma types
export type {
  User,
  Role,
  Permission,
  AuditLog,
  Outlet,
  UserOutlet,
  Category,
  UnitOfMeasure,
  Product,
  ProductVariant,
  PriceLevel,
  Warehouse,
  Stock,
  StockMovement,
  StockAdjustment,
  StockAdjustmentItem,
  StockTransfer,
  StockTransferItem,
  StockOpname,
  StockOpnameItem,
  Customer,
  SalesOrder,
  SalesOrderItem,
  SalesReturn,
  SalesReturnItem,
  Payment,
  Supplier,
  PurchaseOrder,
  PurchaseOrderItem,
  GoodsReceive,
  GoodsReceiveItem,
  PurchaseReturn,
  PurchaseReturnItem,
  SupplierPayment,
  Account,
  ExpenseCategory,
  Transaction,
  License,
} from '@prisma/client';
