import { PrismaClient } from '@prisma/client';

export async function seedRoles(prisma: PrismaClient) {
  // Create default roles
  const ownerRole = await prisma.role.upsert({
    where: { name: 'owner' },
    update: {
      permissions: {
        deleteMany: {},
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'pos', action: 'update' },
          { module: 'pos', action: 'delete' },
          { module: 'products', action: 'create' },
          { module: 'products', action: 'read' },
          { module: 'products', action: 'update' },
          { module: 'products', action: 'delete' },
          { module: 'sales', action: 'create' },
          { module: 'sales', action: 'read' },
          { module: 'sales', action: 'update' },
          { module: 'sales', action: 'delete' },
          { module: 'purchases', action: 'create' },
          { module: 'purchases', action: 'read' },
          { module: 'purchases', action: 'update' },
          { module: 'purchases', action: 'delete' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'inventory', action: 'delete' },
          { module: 'finance', action: 'create' },
          { module: 'finance', action: 'read' },
          { module: 'finance', action: 'update' },
          { module: 'finance', action: 'delete' },
          { module: 'reports', action: 'read' },
          { module: 'settings', action: 'create' },
          { module: 'settings', action: 'read' },
          { module: 'settings', action: 'update' },
          { module: 'settings', action: 'delete' },
          { module: 'users', action: 'create' },
          { module: 'users', action: 'read' },
          { module: 'users', action: 'update' },
          { module: 'users', action: 'delete' },
          { module: 'categories', action: 'create' },
          { module: 'categories', action: 'read' },
          { module: 'categories', action: 'update' },
          { module: 'categories', action: 'delete' },
          { module: 'units', action: 'create' },
          { module: 'units', action: 'read' },
          { module: 'units', action: 'update' },
          { module: 'units', action: 'delete' },
          { module: 'outlets', action: 'create' },
          { module: 'outlets', action: 'read' },
          { module: 'outlets', action: 'update' },
          { module: 'outlets', action: 'delete' },
          { module: 'roles', action: 'create' },
          { module: 'roles', action: 'read' },
          { module: 'roles', action: 'update' },
          { module: 'roles', action: 'delete' },
          { module: 'audit-log', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
          { module: 'suppliers', action: 'delete' },
          { module: 'customers', action: 'create' },
          { module: 'customers', action: 'read' },
          { module: 'customers', action: 'update' },
          { module: 'customers', action: 'delete' },
          { module: 'quotations', action: 'read' },
          { module: 'quotations', action: 'create' },
          { module: 'quotations', action: 'update' },
          { module: 'quotations', action: 'delete' },
          { module: 'quotations', action: 'send' },
          { module: 'quotations', action: 'convert' },
        ],
      },
    },
    create: {
      name: 'owner',
      description: 'Pemilik bisnis dengan akses penuh',
      permissions: {
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'pos', action: 'update' },
          { module: 'pos', action: 'delete' },
          { module: 'products', action: 'create' },
          { module: 'products', action: 'read' },
          { module: 'products', action: 'update' },
          { module: 'products', action: 'delete' },
          { module: 'sales', action: 'create' },
          { module: 'sales', action: 'read' },
          { module: 'sales', action: 'update' },
          { module: 'sales', action: 'delete' },
          { module: 'purchases', action: 'create' },
          { module: 'purchases', action: 'read' },
          { module: 'purchases', action: 'update' },
          { module: 'purchases', action: 'delete' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'inventory', action: 'delete' },
          { module: 'finance', action: 'create' },
          { module: 'finance', action: 'read' },
          { module: 'finance', action: 'update' },
          { module: 'finance', action: 'delete' },
          { module: 'reports', action: 'read' },
          { module: 'settings', action: 'create' },
          { module: 'settings', action: 'read' },
          { module: 'settings', action: 'update' },
          { module: 'settings', action: 'delete' },
          { module: 'users', action: 'create' },
          { module: 'users', action: 'read' },
          { module: 'users', action: 'update' },
          { module: 'users', action: 'delete' },
          { module: 'categories', action: 'create' },
          { module: 'categories', action: 'read' },
          { module: 'categories', action: 'update' },
          { module: 'categories', action: 'delete' },
          { module: 'units', action: 'create' },
          { module: 'units', action: 'read' },
          { module: 'units', action: 'update' },
          { module: 'units', action: 'delete' },
          { module: 'outlets', action: 'create' },
          { module: 'outlets', action: 'read' },
          { module: 'outlets', action: 'update' },
          { module: 'outlets', action: 'delete' },
          { module: 'roles', action: 'create' },
          { module: 'roles', action: 'read' },
          { module: 'roles', action: 'update' },
          { module: 'roles', action: 'delete' },
          { module: 'audit-log', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
          { module: 'suppliers', action: 'delete' },
          { module: 'customers', action: 'create' },
          { module: 'customers', action: 'read' },
          { module: 'customers', action: 'update' },
          { module: 'customers', action: 'delete' },
          { module: 'quotations', action: 'read' },
          { module: 'quotations', action: 'create' },
          { module: 'quotations', action: 'update' },
          { module: 'quotations', action: 'delete' },
          { module: 'quotations', action: 'send' },
          { module: 'quotations', action: 'convert' },
        ],
      },
    },
  });

  const adminRole = await prisma.role.upsert({
    where: { name: 'admin' },
    update: {
      permissions: {
        deleteMany: {},
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'pos', action: 'update' },
          { module: 'pos', action: 'delete' },
          { module: 'products', action: 'create' },
          { module: 'products', action: 'read' },
          { module: 'products', action: 'update' },
          { module: 'products', action: 'delete' },
          { module: 'sales', action: 'create' },
          { module: 'sales', action: 'read' },
          { module: 'sales', action: 'update' },
          { module: 'sales', action: 'delete' },
          { module: 'purchases', action: 'create' },
          { module: 'purchases', action: 'read' },
          { module: 'purchases', action: 'update' },
          { module: 'purchases', action: 'delete' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'inventory', action: 'delete' },
          { module: 'finance', action: 'create' },
          { module: 'finance', action: 'read' },
          { module: 'finance', action: 'update' },
          { module: 'finance', action: 'delete' },
          { module: 'reports', action: 'read' },
          { module: 'settings', action: 'create' },
          { module: 'settings', action: 'read' },
          { module: 'settings', action: 'update' },
          { module: 'settings', action: 'delete' },
          { module: 'users', action: 'create' },
          { module: 'users', action: 'read' },
          { module: 'users', action: 'update' },
          { module: 'users', action: 'delete' },
          { module: 'categories', action: 'create' },
          { module: 'categories', action: 'read' },
          { module: 'categories', action: 'update' },
          { module: 'categories', action: 'delete' },
          { module: 'units', action: 'create' },
          { module: 'units', action: 'read' },
          { module: 'units', action: 'update' },
          { module: 'units', action: 'delete' },
          { module: 'outlets', action: 'create' },
          { module: 'outlets', action: 'read' },
          { module: 'outlets', action: 'update' },
          { module: 'outlets', action: 'delete' },
          { module: 'roles', action: 'create' },
          { module: 'roles', action: 'read' },
          { module: 'roles', action: 'update' },
          { module: 'roles', action: 'delete' },
          { module: 'audit-log', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
          { module: 'suppliers', action: 'delete' },
          { module: 'customers', action: 'create' },
          { module: 'customers', action: 'read' },
          { module: 'customers', action: 'update' },
          { module: 'customers', action: 'delete' },
          { module: 'quotations', action: 'read' },
          { module: 'quotations', action: 'create' },
          { module: 'quotations', action: 'update' },
          { module: 'quotations', action: 'delete' },
          { module: 'quotations', action: 'send' },
          { module: 'quotations', action: 'convert' },
        ],
      },
    },
    create: {
      name: 'admin',
      description: 'Administrator dengan akses manajemen',
      permissions: {
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'pos', action: 'update' },
          { module: 'pos', action: 'delete' },
          { module: 'products', action: 'create' },
          { module: 'products', action: 'read' },
          { module: 'products', action: 'update' },
          { module: 'products', action: 'delete' },
          { module: 'sales', action: 'create' },
          { module: 'sales', action: 'read' },
          { module: 'sales', action: 'update' },
          { module: 'sales', action: 'delete' },
          { module: 'purchases', action: 'create' },
          { module: 'purchases', action: 'read' },
          { module: 'purchases', action: 'update' },
          { module: 'purchases', action: 'delete' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'inventory', action: 'delete' },
          { module: 'finance', action: 'create' },
          { module: 'finance', action: 'read' },
          { module: 'finance', action: 'update' },
          { module: 'finance', action: 'delete' },
          { module: 'reports', action: 'read' },
          { module: 'settings', action: 'create' },
          { module: 'settings', action: 'read' },
          { module: 'settings', action: 'update' },
          { module: 'settings', action: 'delete' },
          { module: 'users', action: 'create' },
          { module: 'users', action: 'read' },
          { module: 'users', action: 'update' },
          { module: 'users', action: 'delete' },
          { module: 'categories', action: 'create' },
          { module: 'categories', action: 'read' },
          { module: 'categories', action: 'update' },
          { module: 'categories', action: 'delete' },
          { module: 'units', action: 'create' },
          { module: 'units', action: 'read' },
          { module: 'units', action: 'update' },
          { module: 'units', action: 'delete' },
          { module: 'outlets', action: 'create' },
          { module: 'outlets', action: 'read' },
          { module: 'outlets', action: 'update' },
          { module: 'outlets', action: 'delete' },
          { module: 'roles', action: 'create' },
          { module: 'roles', action: 'read' },
          { module: 'roles', action: 'update' },
          { module: 'roles', action: 'delete' },
          { module: 'audit-log', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
          { module: 'suppliers', action: 'delete' },
          { module: 'customers', action: 'create' },
          { module: 'customers', action: 'read' },
          { module: 'customers', action: 'update' },
          { module: 'customers', action: 'delete' },
          { module: 'quotations', action: 'read' },
          { module: 'quotations', action: 'create' },
          { module: 'quotations', action: 'update' },
          { module: 'quotations', action: 'delete' },
          { module: 'quotations', action: 'send' },
          { module: 'quotations', action: 'convert' },
        ],
      },
    },
  });

  const kasirRole = await prisma.role.upsert({
    where: { name: 'kasir' },
    update: {
      permissions: {
        deleteMany: {},
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'products', action: 'read' },
          { module: 'categories', action: 'read' },
          { module: 'units', action: 'read' },
          { module: 'sales', action: 'read' },
          { module: 'customers', action: 'create' },
          { module: 'customers', action: 'read' },
        ],
      },
    },
    create: {
      name: 'kasir',
      description: 'Kasir dengan akses POS',
      permissions: {
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'pos', action: 'create' },
          { module: 'pos', action: 'read' },
          { module: 'products', action: 'read' },
          { module: 'categories', action: 'read' },
          { module: 'units', action: 'read' },
          { module: 'sales', action: 'read' },
          { module: 'customers', action: 'read' },
          { module: 'customers', action: 'create' },
        ],
      },
    },
  });

  const gudangRole = await prisma.role.upsert({
    where: { name: 'gudang' },
    update: {
      permissions: {
        deleteMany: {},
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'products', action: 'read' },
          { module: 'categories', action: 'read' },
          { module: 'units', action: 'read' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'purchases', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
        ],
      },
    },
    create: {
      name: 'gudang',
      description: 'Staff gudang dengan akses inventory',
      permissions: {
        create: [
          { module: 'dashboard', action: 'read' },
          { module: 'products', action: 'read' },
          { module: 'categories', action: 'read' },
          { module: 'units', action: 'read' },
          { module: 'inventory', action: 'create' },
          { module: 'inventory', action: 'read' },
          { module: 'inventory', action: 'update' },
          { module: 'purchases', action: 'read' },
          { module: 'suppliers', action: 'create' },
          { module: 'suppliers', action: 'read' },
          { module: 'suppliers', action: 'update' },
        ],
      },
    },
  });

  console.log('✅ Roles created:', {
    ownerRole: ownerRole.name,
    adminRole: adminRole.name,
    kasirRole: kasirRole.name,
    gudangRole: gudangRole.name,
  });

  return { ownerRole, adminRole, kasirRole, gudangRole };
}
