import { PrismaClient } from '@prisma/client';

const fullPermissions = [
  // Core
  { module: 'audit-log', action: 'read' },
  { module: 'users', action: 'read' },
  { module: 'users', action: 'create' },
  { module: 'users', action: 'update' },
  { module: 'users', action: 'delete' },
  { module: 'roles', action: 'read' },
  { module: 'roles', action: 'create' },
  { module: 'roles', action: 'update' },
  { module: 'roles', action: 'delete' },
  { module: 'outlets', action: 'read' },
  { module: 'outlets', action: 'create' },
  { module: 'outlets', action: 'update' },
  { module: 'outlets', action: 'delete' },
  { module: 'license', action: 'read' },
  { module: 'license', action: 'update' },

  // Master Data
  { module: 'products', action: 'read' },
  { module: 'products', action: 'create' },
  { module: 'products', action: 'update' },
  { module: 'products', action: 'delete' },
  { module: 'products', action: 'export' },
  { module: 'categories', action: 'read' },
  { module: 'categories', action: 'create' },
  { module: 'categories', action: 'update' },
  { module: 'categories', action: 'delete' },
  { module: 'units', action: 'read' },
  { module: 'units', action: 'create' },
  { module: 'units', action: 'update' },
  { module: 'units', action: 'delete' },
  { module: 'suppliers', action: 'read' },
  { module: 'suppliers', action: 'create' },
  { module: 'suppliers', action: 'update' },
  { module: 'suppliers', action: 'delete' },
  { module: 'customers', action: 'read' },
  { module: 'customers', action: 'create' },
  { module: 'customers', action: 'update' },
  { module: 'customers', action: 'delete' },
  { module: 'customers', action: 'export' },
  { module: 'warehouses', action: 'read' },
  { module: 'warehouses', action: 'create' },
  { module: 'warehouses', action: 'update' },
  { module: 'warehouses', action: 'delete' },
  { module: 'promotions', action: 'read' },
  { module: 'promotions', action: 'create' },
  { module: 'promotions', action: 'update' },
  { module: 'promotions', action: 'delete' },
  { module: 'payment-terms', action: 'read' },
  { module: 'payment-terms', action: 'create' },
  { module: 'payment-terms', action: 'update' },
  { module: 'payment-terms', action: 'delete' },

  // Business
  { module: 'pos', action: 'read' },
  { module: 'pos', action: 'create' },
  { module: 'pos', action: 'update' },
  { module: 'pos', action: 'delete' },
  { module: 'pos', action: 'void' },
  { module: 'pos', action: 'approve' },
  { module: 'pos', action: 'reject' },
  { module: 'sales', action: 'read' },
  { module: 'sales', action: 'create' },
  { module: 'sales', action: 'update' },
  { module: 'sales', action: 'delete' },
  { module: 'sales', action: 'export' },
  { module: 'sales', action: 'refund' },
  { module: 'sales-orders', action: 'read' },
  { module: 'sales-orders', action: 'create' },
  { module: 'sales-orders', action: 'update' },
  { module: 'sales-orders', action: 'delete' },
  { module: 'sales-orders', action: 'confirm' },
  { module: 'sales-orders', action: 'cancel' },
  { module: 'quotations', action: 'read' },
  { module: 'quotations', action: 'create' },
  { module: 'quotations', action: 'update' },
  { module: 'quotations', action: 'delete' },
  { module: 'quotations', action: 'send' },
  { module: 'quotations', action: 'convert' },
  { module: 'invoices', action: 'read' },
  { module: 'invoices', action: 'create' },
  { module: 'invoices', action: 'update' },
  { module: 'invoices', action: 'delete' },
  { module: 'delivery-orders', action: 'read' },
  { module: 'delivery-orders', action: 'create' },
  { module: 'delivery-orders', action: 'update' },
  { module: 'delivery-orders', action: 'delete' },
  { module: 'customer-payments', action: 'read' },
  { module: 'customer-payments', action: 'create' },
  { module: 'customer-payments', action: 'update' },
  { module: 'customer-payments', action: 'delete' },
  { module: 'sales-returns', action: 'read' },
  { module: 'sales-returns', action: 'create' },
  { module: 'sales-returns', action: 'update' },
  { module: 'sales-returns', action: 'delete' },
  { module: 'sales-returns', action: 'approve' },
  { module: 'sales-returns', action: 'reject' },
  { module: 'purchases', action: 'read' },
  { module: 'purchases', action: 'create' },
  { module: 'purchases', action: 'update' },
  { module: 'purchases', action: 'delete' },
  { module: 'purchase-orders', action: 'read' },
  { module: 'purchase-orders', action: 'create' },
  { module: 'purchase-orders', action: 'update' },
  { module: 'purchase-orders', action: 'delete' },
  { module: 'purchase-orders', action: 'approve' },
  { module: 'purchase-orders', action: 'reject' },
  { module: 'purchase-returns', action: 'read' },
  { module: 'purchase-returns', action: 'create' },
  { module: 'purchase-returns', action: 'update' },
  { module: 'purchase-returns', action: 'delete' },
  { module: 'purchase-returns', action: 'approve' },
  { module: 'purchase-returns', action: 'reject' },
  { module: 'supplier-payments', action: 'read' },
  { module: 'supplier-payments', action: 'create' },
  { module: 'supplier-payments', action: 'update' },
  { module: 'supplier-payments', action: 'delete' },
  { module: 'goods-receive', action: 'read' },
  { module: 'goods-receive', action: 'create' },
  { module: 'goods-receive', action: 'update' },
  { module: 'goods-receive', action: 'delete' },
  { module: 'inventory', action: 'read' },
  { module: 'inventory', action: 'create' },
  { module: 'inventory', action: 'update' },
  { module: 'inventory', action: 'delete' },
  { module: 'stock-adjustments', action: 'read' },
  { module: 'stock-adjustments', action: 'create' },
  { module: 'stock-adjustments', action: 'update' },
  { module: 'stock-adjustments', action: 'delete' },
  { module: 'stock-adjustments', action: 'approve' },
  { module: 'stock-adjustments', action: 'reject' },
  { module: 'stock-transfers', action: 'read' },
  { module: 'stock-transfers', action: 'create' },
  { module: 'stock-transfers', action: 'update' },
  { module: 'stock-transfers', action: 'delete' },
  { module: 'stock-transfers', action: 'approve' },
  { module: 'stock-transfers', action: 'reject' },
  { module: 'stock-opnames', action: 'read' },
  { module: 'stock-opnames', action: 'create' },
  { module: 'stock-opnames', action: 'update' },
  { module: 'stock-opnames', action: 'delete' },
  { module: 'stock-opnames', action: 'finalize' },
  { module: 'stock-opnames', action: 'cancel' },
  { module: 'stock-lots', action: 'read' },
  { module: 'stock-lots', action: 'create' },
  { module: 'stock-lots', action: 'update' },
  { module: 'stock-lots', action: 'delete' },
  { module: 'stock-valuation', action: 'read' },
  { module: 'finance', action: 'read' },
  { module: 'finance', action: 'create' },
  { module: 'finance', action: 'update' },
  { module: 'finance', action: 'delete' },
  { module: 'reports', action: 'read' },
  { module: 'reports', action: 'create' },
  { module: 'reports', action: 'update' },
  { module: 'reports', action: 'delete' },
  { module: 'reports', action: 'export' },
  { module: 'settings', action: 'read' },
  { module: 'settings', action: 'update' },

  // Frontend-only
  { module: 'dashboard', action: 'read' },
  { module: 'dashboard', action: 'update' },
];

const kasirPermissions = [
  { module: 'dashboard', action: 'read' },
  { module: 'pos', action: 'read' },
  { module: 'pos', action: 'create' },
  { module: 'pos', action: 'void' },
  { module: 'sales', action: 'read' },
  { module: 'sales', action: 'create' },
  { module: 'sales-returns', action: 'read' },
  { module: 'sales-returns', action: 'create' },
  { module: 'products', action: 'read' },
  { module: 'categories', action: 'read' },
  { module: 'units', action: 'read' },
  { module: 'customers', action: 'read' },
  { module: 'customers', action: 'create' },
  { module: 'customers', action: 'update' },
  { module: 'promotions', action: 'read' },
  { module: 'payment-terms', action: 'read' },
  { module: 'customer-payments', action: 'read' },
  { module: 'customer-payments', action: 'create' },
];

const gudangPermissions = [
  { module: 'dashboard', action: 'read' },
  // Inventory
  { module: 'inventory', action: 'read' },
  { module: 'inventory', action: 'create' },
  { module: 'inventory', action: 'update' },
  { module: 'inventory', action: 'delete' },
  { module: 'stock-adjustments', action: 'read' },
  { module: 'stock-adjustments', action: 'create' },
  { module: 'stock-adjustments', action: 'update' },
  { module: 'stock-transfers', action: 'read' },
  { module: 'stock-transfers', action: 'create' },
  { module: 'stock-transfers', action: 'update' },
  { module: 'stock-opnames', action: 'read' },
  { module: 'stock-opnames', action: 'create' },
  { module: 'stock-opnames', action: 'update' },
  { module: 'stock-lots', action: 'read' },
  { module: 'stock-lots', action: 'create' },
  { module: 'stock-lots', action: 'update' },
  // Master Data
  { module: 'products', action: 'read' },
  { module: 'categories', action: 'read' },
  { module: 'units', action: 'read' },
  { module: 'warehouses', action: 'read' },
  // Purchases
  { module: 'purchases', action: 'read' },
  { module: 'purchase-orders', action: 'read' },
  { module: 'purchase-returns', action: 'read' },
  { module: 'purchase-returns', action: 'create' },
  { module: 'goods-receive', action: 'read' },
  { module: 'goods-receive', action: 'create' },
  { module: 'goods-receive', action: 'update' },
  { module: 'suppliers', action: 'read' },
  { module: 'suppliers', action: 'create' },
  { module: 'suppliers', action: 'update' },
  // Deliveries
  { module: 'delivery-orders', action: 'read' },
  { module: 'delivery-orders', action: 'create' },
  { module: 'delivery-orders', action: 'update' },
];

export async function seedRoles(prisma: PrismaClient) {
  // Create default roles
  const ownerRole = await prisma.role.upsert({
    where: { name: 'owner' },
    update: {
      permissions: {
        deleteMany: {},
        create: fullPermissions,
      },
    },
    create: {
      name: 'owner',
      description: 'Pemilik bisnis dengan akses penuh',
      permissions: {
        create: fullPermissions,
      },
    },
  });

  const adminRole = await prisma.role.upsert({
    where: { name: 'admin' },
    update: {
      permissions: {
        deleteMany: {},
        create: fullPermissions,
      },
    },
    create: {
      name: 'admin',
      description: 'Administrator dengan akses manajemen',
      permissions: {
        create: fullPermissions,
      },
    },
  });

  const kasirRole = await prisma.role.upsert({
    where: { name: 'kasir' },
    update: {
      permissions: {
        deleteMany: {},
        create: kasirPermissions,
      },
    },
    create: {
      name: 'kasir',
      description: 'Kasir dengan akses POS',
      permissions: {
        create: kasirPermissions,
      },
    },
  });

  const gudangRole = await prisma.role.upsert({
    where: { name: 'gudang' },
    update: {
      permissions: {
        deleteMany: {},
        create: gudangPermissions,
      },
    },
    create: {
      name: 'gudang',
      description: 'Staff gudang dengan akses inventory',
      permissions: {
        create: gudangPermissions,
      },
    },
  });

  console.log('✅ Roles created:', {
    ownerRole: ownerRole.name,
    adminRole: adminRole.name,
    kasirRole: kasirRole.name,
    gudangRole: gudangRole.name,
  });

  return { ownerRole, adminRole, kasirRole, gudangRole };
}
